services:
  app:
    image: yeogido/yeogido-server:latest
    container_name: yeogido-server

    restart: unless-stopped
    pull_policy: always

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    ports:
      - "8080:8080"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.4-alpine
    container_name: yeogido-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data: