spring:
  application:
    name: backend

  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha