spring:
  application:
    name: backend

  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}

app:
  s3:
    bucket: ${S3_BUCKET}

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha