spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

management:
  health:
    db:
      enabled: true
    redis:
      enabled: true
